name: Update and Deploy UI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version file
        run: |
          echo "image_version=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ui
          file: ./ui/Dockerfile
          tags: techwithshubh/finance-ui:${{ env.image_version }}

      - name: Decrypt SSH Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | openssl rsa -passin pass:${{ secrets.SSH_PASSPHRASE }} -out ssh_key

      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ssh_key
          ssh-add ssh_key

      - name: Clone finance-buddy-infra repo
        run: |
          cd ${{ github.workspace }}
          git clone https://github.com/techwithshubh/finance-buddy-infra.git

      - name: Install kustomize CLI
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image version in Kustomization.yml
        run: |
          cd ${{ github.workspace }}/finance-buddy-infra/dev/
          kustomize edit set image FINANCE_BUDDY_UI_IMAGE=techwithshubh/finance-ui:${{ env.image_version }}

      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}/finance-buddy-infra
          git remote remove origin
          git remote add origin git@github.com:techwithshubh/finance-buddy-infra.git
          git config --global user.name "techwithshubh"
          git config --global user.email "techwithshubh@outlook.com"
          git add .
          git commit -m "Update UI image version to ${{ env.image_version }}"
          git push
